[package]
name = "flappy"
authors = ["Sajidur Rahman"]
license = "MIT"
license-file = "LICENSE"
radme = "README.md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
